version: '2'

volumes:
  nextcloud:
  db:

  # Duplicity has a cache so it doesn't have to pull signatures down
  # from the remote everytime an incremental backup is done. This 
  # doesn't need to be backed up.
  duplicity_cache:
  duplicity_cache_gpg:

services:
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:  
    image: nextcloud
    ports:
      - 80:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud_encrypted:/storage
    restart: unless-stopped
  
  peacloud_aws_backup:
    build: ./peacloud_aws_backup
    image: peacloud_aws_backup
    hostname: chunkies
    volumes:
      # Mount the host docker stuff so the backup container
      # can start and stop the db and app containers.
      - /var/run/docker.sock:/var/run/docker.sock
      - duplicity_cache:/root/.cache/duplicity/
      - duplicity_cache_gpg:/root/.gnupg/

      # Mount other volumes readonly
      - db:/mnt/db_volume
      - nextcloud:/mnt/app_volume
      - /mnt/nextcloud_encrypted:/mnt/nextcloud_encrypted:ro

    restart: unless-stopped
